server:
  port: 8085

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/hevinpatel99/microservice-config-server.git
          clone-on-start: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka



# Eureka Client Configuration

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8080/eureka
#
#
#  instance:
#    hostname: localhost
#    prefer-ip-address: true