server:
  port: 8084

# Register Eureka client

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8085


  # Register services iN gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: user-service
#          uri: lb://USER-SERVICE
          uri: http://localhost:8081/
          predicates:
            - Path=/user/**,/v3/api-docs/user
        - id: organization-service
#          uri: lb://ORGANIZATION-SERVICE
          uri: http://localhost:8082/
          predicates:
            - Path=/restaurant/**,/v3/api-docs/organization

        - id: rating-service
#          uri: lb://RATING-SERVICE
          uri: http://localhost:8083/
          predicates:
            - Path=/rating/**,/v3/api-docs/rating
      discovery:
        locator:
          enabled: true






# Okta configuration
#okta:
#  oauth2:
#    issuer: https://dev-13638743.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oafd8s9296PSv6sw5d7
#    client-secret: EXWQO3DD3cZVFEorlCwCf4SD7W-LQTTZ2IZas0Y-izfsrNXf3Kaydo6ULNEukBU4
#    scopes: openid,profile,email,offline_access

  # Eureka Client Configuration

  #eureka:
  #  client:
  #    fetch-registry: true
  #    register-with-eureka: true
  #    service-url:
  #      defaultZone: http://localhost:8080/eureka
  #
  #
  #  instance:
  #    hostname: localhost
  #    prefer-ip-address: true










