server:
  port: 8083

  #  servlet:
  #    context-path: /employee_management_system
  #

  ######### Mysql Config ########
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/role_privileges?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true


  ########## LOGGING ########

Logging:
  level:
    root: info



  ######### MVC prefix & suffix #########

  #  mvc:
  #    view:
  #      prefix: /WEB-INF/view/
  #      suffix: .jsp




  ######### JWT Config #########








